### ISSUE TITLE
Add functionality to run pester and Automatically generate code coverage visualization

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#88]
- [x] Create a common way for which repo can call pester (#90)
- [x] fix style issues such as putting code blocks starts on new line (where possible). (#116)
- [x] Add a common way to automatically detect code and non-code files for code coverage (#(90)
- [x] ~~Add a way to override code and non-code coverage file detection~~ filed #114 
- [x] Add a common way to convert Pester test results object into the code coverage visualizer format (I'm planning on using codecov.io, similarly to PowerShell\PowerShell) (#117)
- [x] Add a common function to upload results to the code coverage visualizer (#117)
- [x] Add deployment documentation(#117)
